var xx = document.querySelector("#items");
console.log(xx.parentElement);
xx.parentElement.style.backgroundColor = "blue";
var pp = document.querySelector("#items");
console.log(pp.lastChild);
pp.lastElementChild.style.color = "#0FAD99";
pp.firstElementChild.textContent = "Hey Look here i am ITEM-1";
console.log(pp.firstChild);
console.log(pp.nextSibling);
console.log(pp.nextElementSibling);
console.log(pp.previousSibling);
pp.previousElementSibling.style.color="#7DB436";
var rak = document.createElement('div');
rak.className = "new li class";
console.log(rak);
//rak.setAttribute('title',"new item added");
var neww = document.createTextNode("i am new div");
rak.appendChild(neww);
var a = document.querySelector('header .container');
var b = document.querySelector('header h1');
a.insertBefore(neww, b);
var g = document.getElementById('items');
console.log(g);
g.innerHTML = '<li>"hello world"</li>' + g.innerHTML;
console.log(g.innerHTML);